Player kw
grahame-student/oxo_tourney pull request #6
Opened 2022-07-04 08:48 UTC by fading-paths-dev

Added a new player for the tourney

2022-07-08 08:48 UTC, grahame-student requested changes
Trying out the code review feature

2022-07-08 08:48 UTC, grahame-student commented on oxo_tourney/tests/player/test_restful_player.py
> -    def test_get_move_diplays_warning_when_grid_size_not_3(self):
Test case reverted

2022-07-11 08:35 UTC, grahame-student commented on requirements.txt
> +requests==2.28.0
@fading-paths-dev the requests library needs to be set to the correct version (check main branch if you're unsure what that should be)

2022-07-11 08:49 UTC, fading-paths-dev commented on requirements.txt
> +requests==2.28.0
@grahame-student done

2022-07-11 08:57 UTC, grahame-student approved these changes

2022-07-11 14:09 UTC, merged